<a href="https://colab.research.google.com/github/moduloous/Skill-lab-files/blob/main/fluidslab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
density = [1, 2, 3]
velocity = [10, 20, 30]

for d, v in zip(density, velocity):
    print(f"Density: {d}, Velocity: {v}")

Density: 1, Velocity: 10
Density: 2, Velocity: 20
Density: 3, Velocity: 30


In [ ]:
rho = 1.225
s = 10.0
Cl = 0.5

velocities = [10, 20, 30, 40, 50]

for v in velocities:
    lift = 0.5 * rho * v**2 * s * Cl
    print(f"Velocity: {v} m/s, Lift: {lift:.2f} N")

Velocity: 10 m/s, Lift: 306.25 N
Velocity: 20 m/s, Lift: 1225.00 N
Velocity: 30 m/s, Lift: 2756.25 N
Velocity: 40 m/s, Lift: 4900.00 N
Velocity: 50 m/s, Lift: 7656.25 N


In [ ]:
density = [1.2, 1.0, 0.8]
height = [10, 20, 30]
gravity = 9.81

for rho, h in zip(density, height):
    pressure = rho * gravity * h
    print(f"Density: {rho} kg/m^3, Height: {h} m, Pressure: {pressure:.2f} Pa")

Density: 1.2 kg/m^3, Height: 10 m, Pressure: 117.72 Pa
Density: 1.0 kg/m^3, Height: 20 m, Pressure: 196.20 Pa
Density: 0.8 kg/m^3, Height: 30 m, Pressure: 235.44 Pa


In [ ]:
# Define some variables
density = [1.2, 1.0, 0.8]  # Densities
velocities = [10, 20, 30] # Velocities
s_values = [10.0, 12.0]   # Wing areas
Cl_values = [0.5, 0.6]    # Lift coefficients

# Placeholder variables (assuming 'i' and 'g' are not standard physical properties in this context)
i_values = [1, 2]
g_values = [9.81, 9.78] # Example gravity values

# Using zip to pair some variables
for rho, v in zip(density, velocities):
    # Nested loop to consider different wing properties and placeholders
    for s, Cl, i, g in zip(s_values, Cl_values, i_values, g_values):
        # Example calculation (e.g., lift calculation combined with other variables)
        lift_or_other_calc = 0.5 * rho * v**2 * s * Cl * i * g # Example combining variables
        print(f"Density: {rho:.2f}, Velocity: {v}, Wing Area: {s}, Cl: {Cl}, i: {i}, g: {g:.2f}, Result: {lift_or_other_calc:.2f}")

Density: 1.20, Velocity: 10, Wing Area: 10.0, Cl: 0.5, i: 1, g: 9.81, Result: 2943.00
Density: 1.20, Velocity: 10, Wing Area: 12.0, Cl: 0.6, i: 2, g: 9.78, Result: 8449.92
Density: 1.00, Velocity: 20, Wing Area: 10.0, Cl: 0.5, i: 1, g: 9.81, Result: 9810.00
Density: 1.00, Velocity: 20, Wing Area: 12.0, Cl: 0.6, i: 2, g: 9.78, Result: 28166.40
Density: 0.80, Velocity: 30, Wing Area: 10.0, Cl: 0.5, i: 1, g: 9.81, Result: 17658.00
Density: 0.80, Velocity: 30, Wing Area: 12.0, Cl: 0.6, i: 2, g: 9.78, Result: 50699.52


In [ ]:
# Define constants
s = 10.0   # Wing area (m^2)
Cl = 0.5   # Lift coefficient

# Define variables
densities = [1.2, 1.0, 0.8]  # Densities
velocities = [10, 20, 30] # Velocities

# Nested loop structure
for i, rho in enumerate(densities):
    print(f"Outer loop - Index: {i}, Density: {rho}")
    # Inner loop over velocities (assuming this is the intended inner loop)
    for v in velocities:
        # Example calculation using constants and variables
        result = 0.5 * rho * v**2 * s * Cl
        print(f"  Inner loop - Velocity: {v}, Result: {result:.2f}")

Outer loop - Index: 0, Density: 1.2
  Inner loop - Velocity: 10, Result: 300.00
  Inner loop - Velocity: 20, Result: 1200.00
  Inner loop - Velocity: 30, Result: 2700.00
Outer loop - Index: 1, Density: 1.0
  Inner loop - Velocity: 10, Result: 250.00
  Inner loop - Velocity: 20, Result: 1000.00
  Inner loop - Velocity: 30, Result: 2250.00
Outer loop - Index: 2, Density: 0.8
  Inner loop - Velocity: 10, Result: 200.00
  Inner loop - Velocity: 20, Result: 800.00
  Inner loop - Velocity: 30, Result: 1800.00


In [ ]:
list1 = [1, 2, 3]
list2 = ['a', 'b', 'c']

for i in range(len(list1)):
    print(f"Element from list1: {list1[i]}, Element from list2: {list2[i]}")

Element from list1: 1, Element from list2: a
Element from list1: 2, Element from list2: b
Element from list1: 3, Element from list2: c


In [ ]:
import numpy as np

# Create a matrix (2x3)
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Create another matrix (3x2)
matrix_b = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Display the matrices
print("Matrix A:")
display(matrix_a)

print("\nMatrix B:")
display(matrix_b)

# Perform matrix multiplication (if dimensions are compatible)
if matrix_a.shape[1] == matrix_b.shape[0]:
    matrix_c = np.dot(matrix_a, matrix_b)
    print("\nMatrix A * Matrix B:")
    display(matrix_c)
else:
    print("\nMatrices cannot be multiplied due to incompatible dimensions.")

Matrix A:


array([[1, 2, 3],
       [4, 5, 6]])


Matrix B:


array([[ 7,  8],
       [ 9, 10],
       [11, 12]])


Matrix A * Matrix B:


array([[ 58,  64],
       [139, 154]])

In [ ]:
import numpy as np

# Create a random 4x4 matrix
random_matrix = np.random.rand(4, 4)

# Display the matrix
print("Random 4x4 Matrix:")
display(random_matrix)

Random 4x4 Matrix:


array([[0.34837588, 0.12888208, 0.34371424, 0.39203679],
       [0.67080735, 0.69908409, 0.67493746, 0.29704758],
       [0.00588288, 0.1476717 , 0.53203896, 0.6136426 ],
       [0.49137948, 0.08337979, 0.83676114, 0.21773962]])

In [ ]:
import numpy as np

# Create a matrix with 16 rows and 1 column
matrix_16x1 = np.array([[i] for i in range(1, 17)])

# Display the matrix and its shape
print("Matrix with 16 rows and 1 column:")
display(matrix_16x1)
print("Shape of the matrix:", matrix_16x1.shape)

Matrix with 16 rows and 1 column:


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

Shape of the matrix: (16, 1)


In [ ]:
import numpy as np

densities = np.array([1.2, 1.3, 1.4])
heights = np.array([10, 20, 30])
g = 9.81


pressures = densities * g * heights

print("Densities:", densities)
print("Heights:", heights)
print("Pressures:", pressures)

Densities: [1.2 1.3 1.4]
Heights: [10 20 30]
Pressures: [117.72 255.06 412.02]


In [ ]:
import numpy as np
height = [10,20,30]
rho = [1.1,2.2,3.2]
h=np.array(height)
r=np.array(rho)
g=9.8
p=h*r*g
b=p.reshape(3,1)
print(p)
print(b)

[107.8 431.2 940.8]
[[107.8]
 [431.2]
 [940.8]]


In [ ]:
height =([2,3,4])
rho=([1.1,1.2,1.3])
g=9.8

import numpy as np

h=np.array(height)

p=h*r*g
for i,h in enumerate(height):
  for j,r in enumerate(rho):

    p=h*r*g
    print(f"Height={h},Rho={r},--> presuure = {p:.2f}")

Height=2,Rho=1.1,--> presuure = 21.56
Height=2,Rho=1.2,--> presuure = 23.52
Height=2,Rho=1.3,--> presuure = 25.48
Height=3,Rho=1.1,--> presuure = 32.34
Height=3,Rho=1.2,--> presuure = 35.28
Height=3,Rho=1.3,--> presuure = 38.22
Height=4,Rho=1.1,--> presuure = 43.12
Height=4,Rho=1.2,--> presuure = 47.04
Height=4,Rho=1.3,--> presuure = 50.96
